app:
  name: IA Support Chatbot
  debug: true
  language_default: es
  similarity_threshold: 0.35
  max_history_turns: 10
  categories: ["ventas", "soporte", "información"]

lm:
    model: "llama-3.2-3b-instruct"
    api_key: 
    base_url: "http://localhost:1234/v1"
